version: '3'
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      SYMFONY_ENV: dev
      DATABASE_HOST: db
      DATABASE_NAME: symfony_development
      DATABASE_USER: docker
      DATABASE_PASSWORD: docker
    volumes:
      - ./:/app
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_development
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

